# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'My_Notes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for My_Notes
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'Alamofire', '~> 5.2.1'

end
